overrides:
  shell-quote: '>=1.8.4'
  esbuild: '>=0.28.1'

allowBuilds:
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  better-sqlite3: true
  esbuild: false
  unrs-resolver: false
  vue-demi: false
