overrides:
  shell-quote: '>=1.8.4'
  esbuild: '>=0.28.1'

allowBuilds:
  '@alosha/vue-select': false
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  better-sqlite3: true
  esbuild: false
  unrs-resolver: false
  vue-demi: false

minimumReleaseAgeExclude:
  - '@alosha/eu-validate@0.1.0'
  - '@alosha/vue-select'
  - '@alosha/xlsx@0.11.0'
